//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.bmecat.bmecat._2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LINE_ITEM_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_ID"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_FEATURES" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRODUCT_COMPONENTS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}QUANTITY"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ORDER_UNIT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PARTIAL_DELIVERY_LIST" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_COMPLETED" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}SUPPLIER_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDER_REFERENCE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SUPPLIER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}CUSTOMER_ORDER_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SHIPMENT_PARTIES_REFERENCE"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}LOGISTIC_DETAILS" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ITEM_UDX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineitemid",
    "productid",
    "productfeatures",
    "productcomponents",
    "quantity",
    "orderunit",
    "partialdeliverylist",
    "deliverycompleted",
    "deliveryreference",
    "supplieridref",
    "orderreference",
    "supplierorderreference",
    "customerorderreference",
    "shipmentpartiesreference",
    "logisticdetails",
    "mimeinfo",
    "remarks",
    "itemudx"
})
@XmlRootElement(name = "DISPATCHNOTIFICATION_ITEM")
public class DISPATCHNOTIFICATIONITEM {

    @XmlElement(name = "LINE_ITEM_ID", required = true)
    protected String lineitemid;
    @XmlElement(name = "PRODUCT_ID", required = true)
    protected PRODUCTID productid;
    @XmlElement(name = "PRODUCT_FEATURES")
    protected PRODUCTFEATURES productfeatures;
    @XmlElement(name = "PRODUCT_COMPONENTS")
    protected PRODUCTCOMPONENTS productcomponents;
    @XmlElement(name = "QUANTITY", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "ORDER_UNIT", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected String orderunit;
    @XmlElement(name = "PARTIAL_DELIVERY_LIST")
    protected PARTIALDELIVERYLIST partialdeliverylist;
    @XmlElement(name = "DELIVERY_COMPLETED")
    protected String deliverycompleted;
    @XmlElement(name = "DELIVERY_REFERENCE")
    protected DELIVERYREFERENCE deliveryreference;
    @XmlElement(name = "SUPPLIER_IDREF", namespace = "http://www.bmecat.org/bmecat/2005")
    protected TypePARTYID supplieridref;
    @XmlElement(name = "ORDER_REFERENCE", required = true)
    protected ORDERREFERENCE orderreference;
    @XmlElement(name = "SUPPLIER_ORDER_REFERENCE")
    protected SUPPLIERORDERREFERENCE supplierorderreference;
    @XmlElement(name = "CUSTOMER_ORDER_REFERENCE")
    protected CUSTOMERORDERREFERENCE customerorderreference;
    @XmlElement(name = "SHIPMENT_PARTIES_REFERENCE", required = true)
    protected SHIPMENTPARTIESREFERENCE shipmentpartiesreference;
    @XmlElement(name = "LOGISTIC_DETAILS")
    protected LOGISTICDETAILS logisticdetails;
    @XmlElement(name = "MIME_INFO")
    protected MIMEINFO mimeinfo;
    @XmlElement(name = "REMARKS")
    protected List<REMARKS> remarks;
    @XmlElement(name = "ITEM_UDX")
    protected UdxITEM itemudx;

    /**
     * Gets the value of the lineitemid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINEITEMID() {
        return lineitemid;
    }

    /**
     * Sets the value of the lineitemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINEITEMID(String value) {
        this.lineitemid = value;
    }

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTID }
     *     
     */
    public PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTID }
     *     
     */
    public void setPRODUCTID(PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productfeatures property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTFEATURES }
     *     
     */
    public PRODUCTFEATURES getPRODUCTFEATURES() {
        return productfeatures;
    }

    /**
     * Sets the value of the productfeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTFEATURES }
     *     
     */
    public void setPRODUCTFEATURES(PRODUCTFEATURES value) {
        this.productfeatures = value;
    }

    /**
     * Gets the value of the productcomponents property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTCOMPONENTS }
     *     
     */
    public PRODUCTCOMPONENTS getPRODUCTCOMPONENTS() {
        return productcomponents;
    }

    /**
     * Sets the value of the productcomponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTCOMPONENTS }
     *     
     */
    public void setPRODUCTCOMPONENTS(PRODUCTCOMPONENTS value) {
        this.productcomponents = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQUANTITY() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQUANTITY(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERUNIT() {
        return orderunit;
    }

    /**
     * Sets the value of the orderunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERUNIT(String value) {
        this.orderunit = value;
    }

    /**
     * Gets the value of the partialdeliverylist property.
     * 
     * @return
     *     possible object is
     *     {@link PARTIALDELIVERYLIST }
     *     
     */
    public PARTIALDELIVERYLIST getPARTIALDELIVERYLIST() {
        return partialdeliverylist;
    }

    /**
     * Sets the value of the partialdeliverylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTIALDELIVERYLIST }
     *     
     */
    public void setPARTIALDELIVERYLIST(PARTIALDELIVERYLIST value) {
        this.partialdeliverylist = value;
    }

    /**
     * Gets the value of the deliverycompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYCOMPLETED() {
        return deliverycompleted;
    }

    /**
     * Sets the value of the deliverycompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYCOMPLETED(String value) {
        this.deliverycompleted = value;
    }

    /**
     * Gets the value of the deliveryreference property.
     * 
     * @return
     *     possible object is
     *     {@link DELIVERYREFERENCE }
     *     
     */
    public DELIVERYREFERENCE getDELIVERYREFERENCE() {
        return deliveryreference;
    }

    /**
     * Sets the value of the deliveryreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELIVERYREFERENCE }
     *     
     */
    public void setDELIVERYREFERENCE(DELIVERYREFERENCE value) {
        this.deliveryreference = value;
    }

    /**
     * Gets the value of the supplieridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getSUPPLIERIDREF() {
        return supplieridref;
    }

    /**
     * Sets the value of the supplieridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setSUPPLIERIDREF(TypePARTYID value) {
        this.supplieridref = value;
    }

    /**
     * Gets the value of the orderreference property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERREFERENCE }
     *     
     */
    public ORDERREFERENCE getORDERREFERENCE() {
        return orderreference;
    }

    /**
     * Sets the value of the orderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERREFERENCE }
     *     
     */
    public void setORDERREFERENCE(ORDERREFERENCE value) {
        this.orderreference = value;
    }

    /**
     * Gets the value of the supplierorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link SUPPLIERORDERREFERENCE }
     *     
     */
    public SUPPLIERORDERREFERENCE getSUPPLIERORDERREFERENCE() {
        return supplierorderreference;
    }

    /**
     * Sets the value of the supplierorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUPPLIERORDERREFERENCE }
     *     
     */
    public void setSUPPLIERORDERREFERENCE(SUPPLIERORDERREFERENCE value) {
        this.supplierorderreference = value;
    }

    /**
     * Gets the value of the customerorderreference property.
     * 
     * @return
     *     possible object is
     *     {@link CUSTOMERORDERREFERENCE }
     *     
     */
    public CUSTOMERORDERREFERENCE getCUSTOMERORDERREFERENCE() {
        return customerorderreference;
    }

    /**
     * Sets the value of the customerorderreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CUSTOMERORDERREFERENCE }
     *     
     */
    public void setCUSTOMERORDERREFERENCE(CUSTOMERORDERREFERENCE value) {
        this.customerorderreference = value;
    }

    /**
     * Gets the value of the shipmentpartiesreference property.
     * 
     * @return
     *     possible object is
     *     {@link SHIPMENTPARTIESREFERENCE }
     *     
     */
    public SHIPMENTPARTIESREFERENCE getSHIPMENTPARTIESREFERENCE() {
        return shipmentpartiesreference;
    }

    /**
     * Sets the value of the shipmentpartiesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SHIPMENTPARTIESREFERENCE }
     *     
     */
    public void setSHIPMENTPARTIESREFERENCE(SHIPMENTPARTIESREFERENCE value) {
        this.shipmentpartiesreference = value;
    }

    /**
     * Gets the value of the logisticdetails property.
     * 
     * @return
     *     possible object is
     *     {@link LOGISTICDETAILS }
     *     
     */
    public LOGISTICDETAILS getLOGISTICDETAILS() {
        return logisticdetails;
    }

    /**
     * Sets the value of the logisticdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOGISTICDETAILS }
     *     
     */
    public void setLOGISTICDETAILS(LOGISTICDETAILS value) {
        this.logisticdetails = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link MIMEINFO }
     *     
     */
    public MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIMEINFO }
     *     
     */
    public void setMIMEINFO(MIMEINFO value) {
        this.mimeinfo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REMARKS }
     * 
     * 
     */
    public List<REMARKS> getREMARKS() {
        if (remarks == null) {
            remarks = new ArrayList<REMARKS>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the itemudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxITEM }
     *     
     */
    public UdxITEM getITEMUDX() {
        return itemudx;
    }

    /**
     * Sets the value of the itemudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxITEM }
     *     
     */
    public void setITEMUDX(UdxITEM value) {
        this.itemudx = value;
    }

}
