//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DISPATCHNOTIFICATION_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DISPATCHNOTIFICATION_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DISPATCHNOTIFICATION_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.opentrans.org/XMLSchema/2.1}typeOPENTRANS_version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dispatchnotificationheader",
    "dispatchnotificationitemlist",
    "dispatchnotificationsummary"
})
@XmlRootElement(name = "DISPATCHNOTIFICATION")
public class DISPATCHNOTIFICATION {

    @XmlElement(name = "DISPATCHNOTIFICATION_HEADER", required = true)
    protected DISPATCHNOTIFICATIONHEADER dispatchnotificationheader;
    @XmlElement(name = "DISPATCHNOTIFICATION_ITEM_LIST", required = true)
    protected DISPATCHNOTIFICATIONITEMLIST dispatchnotificationitemlist;
    @XmlElement(name = "DISPATCHNOTIFICATION_SUMMARY", required = true)
    protected DISPATCHNOTIFICATIONSUMMARY dispatchnotificationsummary;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the dispatchnotificationheader property.
     * 
     * @return
     *     possible object is
     *     {@link DISPATCHNOTIFICATIONHEADER }
     *     
     */
    public DISPATCHNOTIFICATIONHEADER getDISPATCHNOTIFICATIONHEADER() {
        return dispatchnotificationheader;
    }

    /**
     * Sets the value of the dispatchnotificationheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link DISPATCHNOTIFICATIONHEADER }
     *     
     */
    public void setDISPATCHNOTIFICATIONHEADER(DISPATCHNOTIFICATIONHEADER value) {
        this.dispatchnotificationheader = value;
    }

    /**
     * Gets the value of the dispatchnotificationitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link DISPATCHNOTIFICATIONITEMLIST }
     *     
     */
    public DISPATCHNOTIFICATIONITEMLIST getDISPATCHNOTIFICATIONITEMLIST() {
        return dispatchnotificationitemlist;
    }

    /**
     * Sets the value of the dispatchnotificationitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link DISPATCHNOTIFICATIONITEMLIST }
     *     
     */
    public void setDISPATCHNOTIFICATIONITEMLIST(DISPATCHNOTIFICATIONITEMLIST value) {
        this.dispatchnotificationitemlist = value;
    }

    /**
     * Gets the value of the dispatchnotificationsummary property.
     * 
     * @return
     *     possible object is
     *     {@link DISPATCHNOTIFICATIONSUMMARY }
     *     
     */
    public DISPATCHNOTIFICATIONSUMMARY getDISPATCHNOTIFICATIONSUMMARY() {
        return dispatchnotificationsummary;
    }

    /**
     * Sets the value of the dispatchnotificationsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link DISPATCHNOTIFICATIONSUMMARY }
     *     
     */
    public void setDISPATCHNOTIFICATIONSUMMARY(DISPATCHNOTIFICATIONSUMMARY value) {
        this.dispatchnotificationsummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
