//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}INVOICE_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.opentrans.org/XMLSchema/2.1}typeOPENTRANS_version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceheader",
    "invoiceitemlist",
    "invoicesummary"
})
@XmlRootElement(name = "INVOICE")
public class INVOICE {

    @XmlElement(name = "INVOICE_HEADER", required = true)
    protected INVOICEHEADER invoiceheader;
    @XmlElement(name = "INVOICE_ITEM_LIST", required = true)
    protected INVOICEITEMLIST invoiceitemlist;
    @XmlElement(name = "INVOICE_SUMMARY", required = true)
    protected INVOICESUMMARY invoicesummary;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the invoiceheader property.
     * 
     * @return
     *     possible object is
     *     {@link INVOICEHEADER }
     *     
     */
    public INVOICEHEADER getINVOICEHEADER() {
        return invoiceheader;
    }

    /**
     * Sets the value of the invoiceheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVOICEHEADER }
     *     
     */
    public void setINVOICEHEADER(INVOICEHEADER value) {
        this.invoiceheader = value;
    }

    /**
     * Gets the value of the invoiceitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link INVOICEITEMLIST }
     *     
     */
    public INVOICEITEMLIST getINVOICEITEMLIST() {
        return invoiceitemlist;
    }

    /**
     * Sets the value of the invoiceitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVOICEITEMLIST }
     *     
     */
    public void setINVOICEITEMLIST(INVOICEITEMLIST value) {
        this.invoiceitemlist = value;
    }

    /**
     * Gets the value of the invoicesummary property.
     * 
     * @return
     *     possible object is
     *     {@link INVOICESUMMARY }
     *     
     */
    public INVOICESUMMARY getINVOICESUMMARY() {
        return invoicesummary;
    }

    /**
     * Sets the value of the invoicesummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVOICESUMMARY }
     *     
     */
    public void setINVOICESUMMARY(INVOICESUMMARY value) {
        this.invoicesummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
