//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.bmecat.bmecat._2005.MEANSOFTRANSPORT;
import org.bmecat.bmecat._2005.TRANSPORT;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COUNTRY_OF_ORIGIN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TRANSPORT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PACKAGE_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MEANS_OF_TRANSPORT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryoforigin",
    "transport",
    "packageinfo",
    "meansoftransport"
})
@XmlRootElement(name = "LOGISTIC_DETAILS_INFO")
public class LOGISTICDETAILSINFO {

    @XmlElement(name = "COUNTRY_OF_ORIGIN", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<String> countryoforigin;
    @XmlElement(name = "TRANSPORT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<TRANSPORT> transport;
    @XmlElement(name = "PACKAGE_INFO")
    protected PACKAGEINFO packageinfo;
    @XmlElement(name = "MEANS_OF_TRANSPORT", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<MEANSOFTRANSPORT> meansoftransport;

    /**
     * Gets the value of the countryoforigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryoforigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOUNTRYOFORIGIN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCOUNTRYOFORIGIN() {
        if (countryoforigin == null) {
            countryoforigin = new ArrayList<String>();
        }
        return this.countryoforigin;
    }

    /**
     * Gets the value of the transport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRANSPORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSPORT }
     * 
     * 
     */
    public List<TRANSPORT> getTRANSPORT() {
        if (transport == null) {
            transport = new ArrayList<TRANSPORT>();
        }
        return this.transport;
    }

    /**
     * Gets the value of the packageinfo property.
     * 
     * @return
     *     possible object is
     *     {@link PACKAGEINFO }
     *     
     */
    public PACKAGEINFO getPACKAGEINFO() {
        return packageinfo;
    }

    /**
     * Sets the value of the packageinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PACKAGEINFO }
     *     
     */
    public void setPACKAGEINFO(PACKAGEINFO value) {
        this.packageinfo = value;
    }

    /**
     * Gets the value of the meansoftransport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meansoftransport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEANSOFTRANSPORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MEANSOFTRANSPORT }
     * 
     * 
     */
    public List<MEANSOFTRANSPORT> getMEANSOFTRANSPORT() {
        if (meansoftransport == null) {
            meansoftransport = new ArrayList<MEANSOFTRANSPORT>();
        }
        return this.meansoftransport;
    }

}
