//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDERCHANGE_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDERCHANGE_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ORDERCHANGE_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.opentrans.org/XMLSchema/2.1}typeOPENTRANS_version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderchangeheader",
    "orderchangeitemlist",
    "orderchangesummary"
})
@XmlRootElement(name = "ORDERCHANGE")
public class ORDERCHANGE {

    @XmlElement(name = "ORDERCHANGE_HEADER", required = true)
    protected ORDERCHANGEHEADER orderchangeheader;
    @XmlElement(name = "ORDERCHANGE_ITEM_LIST", required = true)
    protected ORDERCHANGEITEMLIST orderchangeitemlist;
    @XmlElement(name = "ORDERCHANGE_SUMMARY", required = true)
    protected ORDERCHANGESUMMARY orderchangesummary;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the orderchangeheader property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERCHANGEHEADER }
     *     
     */
    public ORDERCHANGEHEADER getORDERCHANGEHEADER() {
        return orderchangeheader;
    }

    /**
     * Sets the value of the orderchangeheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERCHANGEHEADER }
     *     
     */
    public void setORDERCHANGEHEADER(ORDERCHANGEHEADER value) {
        this.orderchangeheader = value;
    }

    /**
     * Gets the value of the orderchangeitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERCHANGEITEMLIST }
     *     
     */
    public ORDERCHANGEITEMLIST getORDERCHANGEITEMLIST() {
        return orderchangeitemlist;
    }

    /**
     * Sets the value of the orderchangeitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERCHANGEITEMLIST }
     *     
     */
    public void setORDERCHANGEITEMLIST(ORDERCHANGEITEMLIST value) {
        this.orderchangeitemlist = value;
    }

    /**
     * Gets the value of the orderchangesummary property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERCHANGESUMMARY }
     *     
     */
    public ORDERCHANGESUMMARY getORDERCHANGESUMMARY() {
        return orderchangesummary;
    }

    /**
     * Sets the value of the orderchangesummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERCHANGESUMMARY }
     *     
     */
    public void setORDERCHANGESUMMARY(ORDERCHANGESUMMARY value) {
        this.orderchangesummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
