//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.bmecat.bmecat._2005.PRICEFLAG;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_AMOUNT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}ALLOW_OR_CHARGES_FIX" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_FLAG" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}TAX_DETAILS_FIX" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRICE_QUANTITY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}PRICE_BASE_FIX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priceamount",
    "alloworchargesfix",
    "priceflag",
    "taxdetailsfix",
    "pricequantity",
    "pricebasefix"
})
@XmlRootElement(name = "PRODUCT_PRICE_FIX")
public class PRODUCTPRICEFIX {

    @XmlElement(name = "PRICE_AMOUNT", namespace = "http://www.bmecat.org/bmecat/2005", required = true)
    protected BigDecimal priceamount;
    @XmlElement(name = "ALLOW_OR_CHARGES_FIX")
    protected ALLOWORCHARGESFIX alloworchargesfix;
    @XmlElement(name = "PRICE_FLAG", namespace = "http://www.bmecat.org/bmecat/2005")
    protected List<PRICEFLAG> priceflag;
    @XmlElement(name = "TAX_DETAILS_FIX")
    protected List<TAXDETAILSFIX> taxdetailsfix;
    @XmlElement(name = "PRICE_QUANTITY", namespace = "http://www.bmecat.org/bmecat/2005", defaultValue = "1")
    protected BigDecimal pricequantity;
    @XmlElement(name = "PRICE_BASE_FIX")
    protected PRICEBASEFIX pricebasefix;

    /**
     * Gets the value of the priceamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEAMOUNT() {
        return priceamount;
    }

    /**
     * Sets the value of the priceamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEAMOUNT(BigDecimal value) {
        this.priceamount = value;
    }

    /**
     * Gets the value of the alloworchargesfix property.
     * 
     * @return
     *     possible object is
     *     {@link ALLOWORCHARGESFIX }
     *     
     */
    public ALLOWORCHARGESFIX getALLOWORCHARGESFIX() {
        return alloworchargesfix;
    }

    /**
     * Sets the value of the alloworchargesfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link ALLOWORCHARGESFIX }
     *     
     */
    public void setALLOWORCHARGESFIX(ALLOWORCHARGESFIX value) {
        this.alloworchargesfix = value;
    }

    /**
     * Gets the value of the priceflag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceflag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRICEFLAG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRICEFLAG }
     * 
     * 
     */
    public List<PRICEFLAG> getPRICEFLAG() {
        if (priceflag == null) {
            priceflag = new ArrayList<PRICEFLAG>();
        }
        return this.priceflag;
    }

    /**
     * Gets the value of the taxdetailsfix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxdetailsfix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAXDETAILSFIX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAXDETAILSFIX }
     * 
     * 
     */
    public List<TAXDETAILSFIX> getTAXDETAILSFIX() {
        if (taxdetailsfix == null) {
            taxdetailsfix = new ArrayList<TAXDETAILSFIX>();
        }
        return this.taxdetailsfix;
    }

    /**
     * Gets the value of the pricequantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPRICEQUANTITY() {
        return pricequantity;
    }

    /**
     * Sets the value of the pricequantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPRICEQUANTITY(BigDecimal value) {
        this.pricequantity = value;
    }

    /**
     * Gets the value of the pricebasefix property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEBASEFIX }
     *     
     */
    public PRICEBASEFIX getPRICEBASEFIX() {
        return pricebasefix;
    }

    /**
     * Sets the value of the pricebasefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEBASEFIX }
     *     
     */
    public void setPRICEBASEFIX(PRICEBASEFIX value) {
        this.pricebasefix = value;
    }

}
