//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RECEIPTACKNOWLEDGEMENT_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RECEIPTACKNOWLEDGEMENT_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RECEIPTACKNOWLEDGEMENT_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.opentrans.org/XMLSchema/2.1}typeOPENTRANS_version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiptacknowledgementheader",
    "receiptacknowledgementitemlist",
    "receiptacknowledgementsummary"
})
@XmlRootElement(name = "RECEIPTACKNOWLEDGEMENT")
public class RECEIPTACKNOWLEDGEMENT {

    @XmlElement(name = "RECEIPTACKNOWLEDGEMENT_HEADER", required = true)
    protected RECEIPTACKNOWLEDGEMENTHEADER receiptacknowledgementheader;
    @XmlElement(name = "RECEIPTACKNOWLEDGEMENT_ITEM_LIST", required = true)
    protected RECEIPTACKNOWLEDGEMENTITEMLIST receiptacknowledgementitemlist;
    @XmlElement(name = "RECEIPTACKNOWLEDGEMENT_SUMMARY", required = true)
    protected RECEIPTACKNOWLEDGEMENTSUMMARY receiptacknowledgementsummary;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the receiptacknowledgementheader property.
     * 
     * @return
     *     possible object is
     *     {@link RECEIPTACKNOWLEDGEMENTHEADER }
     *     
     */
    public RECEIPTACKNOWLEDGEMENTHEADER getRECEIPTACKNOWLEDGEMENTHEADER() {
        return receiptacknowledgementheader;
    }

    /**
     * Sets the value of the receiptacknowledgementheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RECEIPTACKNOWLEDGEMENTHEADER }
     *     
     */
    public void setRECEIPTACKNOWLEDGEMENTHEADER(RECEIPTACKNOWLEDGEMENTHEADER value) {
        this.receiptacknowledgementheader = value;
    }

    /**
     * Gets the value of the receiptacknowledgementitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link RECEIPTACKNOWLEDGEMENTITEMLIST }
     *     
     */
    public RECEIPTACKNOWLEDGEMENTITEMLIST getRECEIPTACKNOWLEDGEMENTITEMLIST() {
        return receiptacknowledgementitemlist;
    }

    /**
     * Sets the value of the receiptacknowledgementitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link RECEIPTACKNOWLEDGEMENTITEMLIST }
     *     
     */
    public void setRECEIPTACKNOWLEDGEMENTITEMLIST(RECEIPTACKNOWLEDGEMENTITEMLIST value) {
        this.receiptacknowledgementitemlist = value;
    }

    /**
     * Gets the value of the receiptacknowledgementsummary property.
     * 
     * @return
     *     possible object is
     *     {@link RECEIPTACKNOWLEDGEMENTSUMMARY }
     *     
     */
    public RECEIPTACKNOWLEDGEMENTSUMMARY getRECEIPTACKNOWLEDGEMENTSUMMARY() {
        return receiptacknowledgementsummary;
    }

    /**
     * Sets the value of the receiptacknowledgementsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RECEIPTACKNOWLEDGEMENTSUMMARY }
     *     
     */
    public void setRECEIPTACKNOWLEDGEMENTSUMMARY(RECEIPTACKNOWLEDGEMENTSUMMARY value) {
        this.receiptacknowledgementsummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
