//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RFQ_HEADER"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RFQ_ITEM_LIST"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}RFQ_SUMMARY"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.opentrans.org/XMLSchema/2.1}typeOPENTRANS_version" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *             &lt;enumeration value="standard"/>
 *             &lt;enumeration value="express"/>
 *             &lt;enumeration value="release"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rfqheader",
    "rfqitemlist",
    "rfqsummary"
})
@XmlRootElement(name = "RFQ")
public class RFQ {

    @XmlElement(name = "RFQ_HEADER", required = true)
    protected RFQHEADER rfqheader;
    @XmlElement(name = "RFQ_ITEM_LIST", required = true)
    protected RFQITEMLIST rfqitemlist;
    @XmlElement(name = "RFQ_SUMMARY", required = true)
    protected RFQSUMMARY rfqsummary;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the rfqheader property.
     * 
     * @return
     *     possible object is
     *     {@link RFQHEADER }
     *     
     */
    public RFQHEADER getRFQHEADER() {
        return rfqheader;
    }

    /**
     * Sets the value of the rfqheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RFQHEADER }
     *     
     */
    public void setRFQHEADER(RFQHEADER value) {
        this.rfqheader = value;
    }

    /**
     * Gets the value of the rfqitemlist property.
     * 
     * @return
     *     possible object is
     *     {@link RFQITEMLIST }
     *     
     */
    public RFQITEMLIST getRFQITEMLIST() {
        return rfqitemlist;
    }

    /**
     * Sets the value of the rfqitemlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link RFQITEMLIST }
     *     
     */
    public void setRFQITEMLIST(RFQITEMLIST value) {
        this.rfqitemlist = value;
    }

    /**
     * Gets the value of the rfqsummary property.
     * 
     * @return
     *     possible object is
     *     {@link RFQSUMMARY }
     *     
     */
    public RFQSUMMARY getRFQSUMMARY() {
        return rfqsummary;
    }

    /**
     * Sets the value of the rfqsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RFQSUMMARY }
     *     
     */
    public void setRFQSUMMARY(RFQSUMMARY value) {
        this.rfqsummary = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
