//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.bmecat.bmecat._2005.TypePARTYID;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERY_IDREF"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}FINAL_DELIVERY_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}DELIVERER_IDREF" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryidref",
    "finaldeliveryidref",
    "delivereridref"
})
@XmlRootElement(name = "SHIPMENT_PARTIES_REFERENCE")
public class SHIPMENTPARTIESREFERENCE {

    @XmlElement(name = "DELIVERY_IDREF", required = true)
    protected TypePARTYID deliveryidref;
    @XmlElement(name = "FINAL_DELIVERY_IDREF")
    protected TypePARTYID finaldeliveryidref;
    @XmlElement(name = "DELIVERER_IDREF")
    protected TypePARTYID delivereridref;

    /**
     * Gets the value of the deliveryidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getDELIVERYIDREF() {
        return deliveryidref;
    }

    /**
     * Sets the value of the deliveryidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setDELIVERYIDREF(TypePARTYID value) {
        this.deliveryidref = value;
    }

    /**
     * Gets the value of the finaldeliveryidref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getFINALDELIVERYIDREF() {
        return finaldeliveryidref;
    }

    /**
     * Sets the value of the finaldeliveryidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setFINALDELIVERYIDREF(TypePARTYID value) {
        this.finaldeliveryidref = value;
    }

    /**
     * Gets the value of the delivereridref property.
     * 
     * @return
     *     possible object is
     *     {@link TypePARTYID }
     *     
     */
    public TypePARTYID getDELIVERERIDREF() {
        return delivereridref;
    }

    /**
     * Sets the value of the delivereridref property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypePARTYID }
     *     
     */
    public void setDELIVERERIDREF(TypePARTYID value) {
        this.delivereridref = value;
    }

}
