//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}MIME"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}SIGNATURE_IN_ORIGINAL"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}XML_SIGNATURE"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mime",
    "signatureinoriginal",
    "xmlsignature"
})
@XmlRootElement(name = "SIGNATURE")
public class SIGNATURE {

    @XmlElement(name = "MIME")
    protected MIME mime;
    @XmlElement(name = "SIGNATURE_IN_ORIGINAL")
    protected String signatureinoriginal;
    @XmlElement(name = "XML_SIGNATURE")
    protected XMLSIGNATURE xmlsignature;

    /**
     * Gets the value of the mime property.
     * 
     * @return
     *     possible object is
     *     {@link MIME }
     *     
     */
    public MIME getMIME() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIME }
     *     
     */
    public void setMIME(MIME value) {
        this.mime = value;
    }

    /**
     * Gets the value of the signatureinoriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIGNATUREINORIGINAL() {
        return signatureinoriginal;
    }

    /**
     * Sets the value of the signatureinoriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIGNATUREINORIGINAL(String value) {
        this.signatureinoriginal = value;
    }

    /**
     * Gets the value of the xmlsignature property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSIGNATURE }
     *     
     */
    public XMLSIGNATURE getXMLSIGNATURE() {
        return xmlsignature;
    }

    /**
     * Sets the value of the xmlsignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSIGNATURE }
     *     
     */
    public void setXMLSIGNATURE(XMLSIGNATURE value) {
        this.xmlsignature = value;
    }

}
