//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.opentrans.xmlschema._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}XML_FORMAT"/>
 *         &lt;element ref="{http://www.opentrans.org/XMLSchema/2.1}REPORT_UDX"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xmlformat",
    "reportudx"
})
@XmlRootElement(name = "VERIFICATION_XMLREPORT")
public class VERIFICATIONXMLREPORT {

    @XmlElement(name = "XML_FORMAT", required = true)
    protected String xmlformat;
    @XmlElement(name = "REPORT_UDX", required = true)
    protected UdxREPORT reportudx;

    /**
     * Gets the value of the xmlformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLFORMAT() {
        return xmlformat;
    }

    /**
     * Sets the value of the xmlformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLFORMAT(String value) {
        this.xmlformat = value;
    }

    /**
     * Gets the value of the reportudx property.
     * 
     * @return
     *     possible object is
     *     {@link UdxREPORT }
     *     
     */
    public UdxREPORT getREPORTUDX() {
        return reportudx;
    }

    /**
     * Sets the value of the reportudx property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdxREPORT }
     *     
     */
    public void setREPORTUDX(UdxREPORT value) {
        this.reportudx = value;
    }

}
