//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.17 at 10:18:46 PM CEST 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._128;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import un.unece.uncefact.data.standard.qualifieddatatype._128.CurrencyCodeType;


/**
 * Header Trade Settlement
 * 
 * <p>Java class for HeaderTradeSettlementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderTradeSettlementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxCurrencyCode" type="{urn:un:unece:uncefact:data:standard:QualifiedDataType:128}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="OrderCurrencyCode" type="{urn:un:unece:uncefact:data:standard:QualifiedDataType:128}CurrencyCodeType"/>
 *         &lt;element name="InvoiceCurrencyCode" type="{urn:un:unece:uncefact:data:standard:QualifiedDataType:128}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="InvoicerTradeParty" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradePartyType" minOccurs="0"/>
 *         &lt;element name="InvoiceeTradeParty" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradePartyType" minOccurs="0"/>
 *         &lt;element name="SpecifiedTradeSettlementPaymentMeans" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradeSettlementPaymentMeansType" minOccurs="0"/>
 *         &lt;element name="ApplicableTradeTax" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradeTaxType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecifiedTradeAllowanceCharge" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradeAllowanceChargeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecifiedLogisticsServiceCharge" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}LogisticsServiceChargeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecifiedTradePaymentTerms" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradePaymentTermsType" minOccurs="0"/>
 *         &lt;element name="SpecifiedTradeSettlementHeaderMonetarySummation" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradeSettlementHeaderMonetarySummationType"/>
 *         &lt;element name="ReceivableSpecifiedTradeAccountingAccount" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128}TradeAccountingAccountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderTradeSettlementType", propOrder = {
    "taxCurrencyCode",
    "orderCurrencyCode",
    "invoiceCurrencyCode",
    "invoicerTradeParty",
    "invoiceeTradeParty",
    "specifiedTradeSettlementPaymentMeans",
    "applicableTradeTax",
    "specifiedTradeAllowanceCharge",
    "specifiedLogisticsServiceCharge",
    "specifiedTradePaymentTerms",
    "specifiedTradeSettlementHeaderMonetarySummation",
    "receivableSpecifiedTradeAccountingAccount"
})
public class HeaderTradeSettlementType {

    @XmlElement(name = "TaxCurrencyCode")
    protected CurrencyCodeType taxCurrencyCode;
    @XmlElement(name = "OrderCurrencyCode", required = true)
    protected CurrencyCodeType orderCurrencyCode;
    @XmlElement(name = "InvoiceCurrencyCode")
    protected CurrencyCodeType invoiceCurrencyCode;
    @XmlElement(name = "InvoicerTradeParty")
    protected TradePartyType invoicerTradeParty;
    @XmlElement(name = "InvoiceeTradeParty")
    protected TradePartyType invoiceeTradeParty;
    @XmlElement(name = "SpecifiedTradeSettlementPaymentMeans")
    protected TradeSettlementPaymentMeansType specifiedTradeSettlementPaymentMeans;
    @XmlElement(name = "ApplicableTradeTax")
    protected List<TradeTaxType> applicableTradeTax;
    @XmlElement(name = "SpecifiedTradeAllowanceCharge")
    protected List<TradeAllowanceChargeType> specifiedTradeAllowanceCharge;
    @XmlElement(name = "SpecifiedLogisticsServiceCharge")
    protected List<LogisticsServiceChargeType> specifiedLogisticsServiceCharge;
    @XmlElement(name = "SpecifiedTradePaymentTerms")
    protected TradePaymentTermsType specifiedTradePaymentTerms;
    @XmlElement(name = "SpecifiedTradeSettlementHeaderMonetarySummation", required = true)
    protected TradeSettlementHeaderMonetarySummationType specifiedTradeSettlementHeaderMonetarySummation;
    @XmlElement(name = "ReceivableSpecifiedTradeAccountingAccount")
    protected TradeAccountingAccountType receivableSpecifiedTradeAccountingAccount;

    /**
     * Gets the value of the taxCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getTaxCurrencyCode() {
        return taxCurrencyCode;
    }

    /**
     * Sets the value of the taxCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setTaxCurrencyCode(CurrencyCodeType value) {
        this.taxCurrencyCode = value;
    }

    /**
     * Gets the value of the orderCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getOrderCurrencyCode() {
        return orderCurrencyCode;
    }

    /**
     * Sets the value of the orderCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setOrderCurrencyCode(CurrencyCodeType value) {
        this.orderCurrencyCode = value;
    }

    /**
     * Gets the value of the invoiceCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getInvoiceCurrencyCode() {
        return invoiceCurrencyCode;
    }

    /**
     * Sets the value of the invoiceCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setInvoiceCurrencyCode(CurrencyCodeType value) {
        this.invoiceCurrencyCode = value;
    }

    /**
     * Gets the value of the invoicerTradeParty property.
     * 
     * @return
     *     possible object is
     *     {@link TradePartyType }
     *     
     */
    public TradePartyType getInvoicerTradeParty() {
        return invoicerTradeParty;
    }

    /**
     * Sets the value of the invoicerTradeParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePartyType }
     *     
     */
    public void setInvoicerTradeParty(TradePartyType value) {
        this.invoicerTradeParty = value;
    }

    /**
     * Gets the value of the invoiceeTradeParty property.
     * 
     * @return
     *     possible object is
     *     {@link TradePartyType }
     *     
     */
    public TradePartyType getInvoiceeTradeParty() {
        return invoiceeTradeParty;
    }

    /**
     * Sets the value of the invoiceeTradeParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePartyType }
     *     
     */
    public void setInvoiceeTradeParty(TradePartyType value) {
        this.invoiceeTradeParty = value;
    }

    /**
     * Gets the value of the specifiedTradeSettlementPaymentMeans property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSettlementPaymentMeansType }
     *     
     */
    public TradeSettlementPaymentMeansType getSpecifiedTradeSettlementPaymentMeans() {
        return specifiedTradeSettlementPaymentMeans;
    }

    /**
     * Sets the value of the specifiedTradeSettlementPaymentMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSettlementPaymentMeansType }
     *     
     */
    public void setSpecifiedTradeSettlementPaymentMeans(TradeSettlementPaymentMeansType value) {
        this.specifiedTradeSettlementPaymentMeans = value;
    }

    /**
     * Gets the value of the applicableTradeTax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicableTradeTax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableTradeTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradeTaxType }
     * 
     * 
     */
    public List<TradeTaxType> getApplicableTradeTax() {
        if (applicableTradeTax == null) {
            applicableTradeTax = new ArrayList<TradeTaxType>();
        }
        return this.applicableTradeTax;
    }

    /**
     * Gets the value of the specifiedTradeAllowanceCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specifiedTradeAllowanceCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecifiedTradeAllowanceCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradeAllowanceChargeType }
     * 
     * 
     */
    public List<TradeAllowanceChargeType> getSpecifiedTradeAllowanceCharge() {
        if (specifiedTradeAllowanceCharge == null) {
            specifiedTradeAllowanceCharge = new ArrayList<TradeAllowanceChargeType>();
        }
        return this.specifiedTradeAllowanceCharge;
    }

    /**
     * Gets the value of the specifiedLogisticsServiceCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specifiedLogisticsServiceCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecifiedLogisticsServiceCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogisticsServiceChargeType }
     * 
     * 
     */
    public List<LogisticsServiceChargeType> getSpecifiedLogisticsServiceCharge() {
        if (specifiedLogisticsServiceCharge == null) {
            specifiedLogisticsServiceCharge = new ArrayList<LogisticsServiceChargeType>();
        }
        return this.specifiedLogisticsServiceCharge;
    }

    /**
     * Gets the value of the specifiedTradePaymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link TradePaymentTermsType }
     *     
     */
    public TradePaymentTermsType getSpecifiedTradePaymentTerms() {
        return specifiedTradePaymentTerms;
    }

    /**
     * Sets the value of the specifiedTradePaymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePaymentTermsType }
     *     
     */
    public void setSpecifiedTradePaymentTerms(TradePaymentTermsType value) {
        this.specifiedTradePaymentTerms = value;
    }

    /**
     * Gets the value of the specifiedTradeSettlementHeaderMonetarySummation property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSettlementHeaderMonetarySummationType }
     *     
     */
    public TradeSettlementHeaderMonetarySummationType getSpecifiedTradeSettlementHeaderMonetarySummation() {
        return specifiedTradeSettlementHeaderMonetarySummation;
    }

    /**
     * Sets the value of the specifiedTradeSettlementHeaderMonetarySummation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSettlementHeaderMonetarySummationType }
     *     
     */
    public void setSpecifiedTradeSettlementHeaderMonetarySummation(TradeSettlementHeaderMonetarySummationType value) {
        this.specifiedTradeSettlementHeaderMonetarySummation = value;
    }

    /**
     * Gets the value of the receivableSpecifiedTradeAccountingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TradeAccountingAccountType }
     *     
     */
    public TradeAccountingAccountType getReceivableSpecifiedTradeAccountingAccount() {
        return receivableSpecifiedTradeAccountingAccount;
    }

    /**
     * Sets the value of the receivableSpecifiedTradeAccountingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeAccountingAccountType }
     *     
     */
    public void setReceivableSpecifiedTradeAccountingAccount(TradeAccountingAccountType value) {
        this.receivableSpecifiedTradeAccountingAccount = value;
    }

}
