//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 10:16:57 PM CET 
//


package un.unece.uncefact.codelist.standard.unece.dutytaxfeetypecode.d19b;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DutyTaxFeeTypeCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DutyTaxFeeTypeCodeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="AAA"/>
 *     &lt;enumeration value="AAB"/>
 *     &lt;enumeration value="AAC"/>
 *     &lt;enumeration value="AAD"/>
 *     &lt;enumeration value="AAE"/>
 *     &lt;enumeration value="AAF"/>
 *     &lt;enumeration value="AAG"/>
 *     &lt;enumeration value="AAH"/>
 *     &lt;enumeration value="AAI"/>
 *     &lt;enumeration value="AAJ"/>
 *     &lt;enumeration value="AAK"/>
 *     &lt;enumeration value="AAL"/>
 *     &lt;enumeration value="AAM"/>
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="BOL"/>
 *     &lt;enumeration value="CAP"/>
 *     &lt;enumeration value="CAR"/>
 *     &lt;enumeration value="COC"/>
 *     &lt;enumeration value="CST"/>
 *     &lt;enumeration value="CUD"/>
 *     &lt;enumeration value="CVD"/>
 *     &lt;enumeration value="ENV"/>
 *     &lt;enumeration value="EXC"/>
 *     &lt;enumeration value="EXP"/>
 *     &lt;enumeration value="FET"/>
 *     &lt;enumeration value="FRE"/>
 *     &lt;enumeration value="GCN"/>
 *     &lt;enumeration value="GST"/>
 *     &lt;enumeration value="ILL"/>
 *     &lt;enumeration value="IMP"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="LAC"/>
 *     &lt;enumeration value="LCN"/>
 *     &lt;enumeration value="LDP"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="LST"/>
 *     &lt;enumeration value="MCA"/>
 *     &lt;enumeration value="MCD"/>
 *     &lt;enumeration value="OTH"/>
 *     &lt;enumeration value="PDB"/>
 *     &lt;enumeration value="PDC"/>
 *     &lt;enumeration value="PRF"/>
 *     &lt;enumeration value="SCN"/>
 *     &lt;enumeration value="SSS"/>
 *     &lt;enumeration value="STT"/>
 *     &lt;enumeration value="SUP"/>
 *     &lt;enumeration value="SUR"/>
 *     &lt;enumeration value="SWT"/>
 *     &lt;enumeration value="TAC"/>
 *     &lt;enumeration value="TOT"/>
 *     &lt;enumeration value="TOX"/>
 *     &lt;enumeration value="TTA"/>
 *     &lt;enumeration value="VAD"/>
 *     &lt;enumeration value="VAT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DutyTaxFeeTypeCodeContentType", namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:DutyTaxFeeTypeCode:D19B")
@XmlEnum
public enum DutyTaxFeeTypeCodeContentType {

    AAA,
    AAB,
    AAC,
    AAD,
    AAE,
    AAF,
    AAG,
    AAH,
    AAI,
    AAJ,
    AAK,
    AAL,
    AAM,
    ADD,
    BOL,
    CAP,
    CAR,
    COC,
    CST,
    CUD,
    CVD,
    ENV,
    EXC,
    EXP,
    FET,
    FRE,
    GCN,
    GST,
    ILL,
    IMP,
    IND,
    LAC,
    LCN,
    LDP,
    LOC,
    LST,
    MCA,
    MCD,
    OTH,
    PDB,
    PDC,
    PRF,
    SCN,
    SSS,
    STT,
    SUP,
    SUR,
    SWT,
    TAC,
    TOT,
    TOX,
    TTA,
    VAD,
    VAT;

    public String value() {
        return name();
    }

    public static DutyTaxFeeTypeCodeContentType fromValue(String v) {
        return valueOf(v);
    }

}
