//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.10 at 09:19:13 PM CET 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._103;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import un.unece.uncefact.data.standard.unqualifieddatatype._103.IndicatorType;


/**
 * Exchanged Document Context
 * 
 * <p>Java class for ExchangedDocumentContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExchangedDocumentContextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestIndicator" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:103}IndicatorType" minOccurs="0"/>
 *         &lt;element name="BusinessProcessSpecifiedDocumentContextParameter" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}DocumentContextParameterType" minOccurs="0"/>
 *         &lt;element name="GuidelineSpecifiedDocumentContextParameter" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}DocumentContextParameterType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangedDocumentContextType", propOrder = {
    "testIndicator",
    "businessProcessSpecifiedDocumentContextParameter",
    "guidelineSpecifiedDocumentContextParameter"
})
public class ExchangedDocumentContextType {

    @XmlElement(name = "TestIndicator")
    protected IndicatorType testIndicator;
    @XmlElement(name = "BusinessProcessSpecifiedDocumentContextParameter")
    protected DocumentContextParameterType businessProcessSpecifiedDocumentContextParameter;
    @XmlElement(name = "GuidelineSpecifiedDocumentContextParameter", required = true)
    protected DocumentContextParameterType guidelineSpecifiedDocumentContextParameter;

    /**
     * Gets the value of the testIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorType }
     *     
     */
    public IndicatorType getTestIndicator() {
        return testIndicator;
    }

    /**
     * Sets the value of the testIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorType }
     *     
     */
    public void setTestIndicator(IndicatorType value) {
        this.testIndicator = value;
    }

    /**
     * Gets the value of the businessProcessSpecifiedDocumentContextParameter property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentContextParameterType }
     *     
     */
    public DocumentContextParameterType getBusinessProcessSpecifiedDocumentContextParameter() {
        return businessProcessSpecifiedDocumentContextParameter;
    }

    /**
     * Sets the value of the businessProcessSpecifiedDocumentContextParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentContextParameterType }
     *     
     */
    public void setBusinessProcessSpecifiedDocumentContextParameter(DocumentContextParameterType value) {
        this.businessProcessSpecifiedDocumentContextParameter = value;
    }

    /**
     * Gets the value of the guidelineSpecifiedDocumentContextParameter property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentContextParameterType }
     *     
     */
    public DocumentContextParameterType getGuidelineSpecifiedDocumentContextParameter() {
        return guidelineSpecifiedDocumentContextParameter;
    }

    /**
     * Sets the value of the guidelineSpecifiedDocumentContextParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentContextParameterType }
     *     
     */
    public void setGuidelineSpecifiedDocumentContextParameter(DocumentContextParameterType value) {
        this.guidelineSpecifiedDocumentContextParameter = value;
    }

}
