//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.10 at 09:19:13 PM CET 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._103;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import un.unece.uncefact.data.standard.unqualifieddatatype._103.TextType;


/**
 * Header Trade Agreement
 * 
 * <p>Java class for HeaderTradeAgreementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderTradeAgreementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerReference" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:103}TextType" minOccurs="0"/>
 *         &lt;element name="SellerTradeParty" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradePartyType"/>
 *         &lt;element name="BuyerTradeParty" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradePartyType"/>
 *         &lt;element name="ApplicableTradeDeliveryTerms" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradeDeliveryTermsType" minOccurs="0"/>
 *         &lt;element name="BuyerOrderReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="QuotationReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="ContractReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="BlanketOrderReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="PreviousOrderReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="PreviousOrderChangeReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *         &lt;element name="PreviousOrderResponseReferencedDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedDocumentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderTradeAgreementType", propOrder = {
    "buyerReference",
    "sellerTradeParty",
    "buyerTradeParty",
    "applicableTradeDeliveryTerms",
    "buyerOrderReferencedDocument",
    "quotationReferencedDocument",
    "contractReferencedDocument",
    "blanketOrderReferencedDocument",
    "previousOrderReferencedDocument",
    "previousOrderChangeReferencedDocument",
    "previousOrderResponseReferencedDocument"
})
public class HeaderTradeAgreementType {

    @XmlElement(name = "BuyerReference")
    protected TextType buyerReference;
    @XmlElement(name = "SellerTradeParty", required = true)
    protected TradePartyType sellerTradeParty;
    @XmlElement(name = "BuyerTradeParty", required = true)
    protected TradePartyType buyerTradeParty;
    @XmlElement(name = "ApplicableTradeDeliveryTerms")
    protected TradeDeliveryTermsType applicableTradeDeliveryTerms;
    @XmlElement(name = "BuyerOrderReferencedDocument")
    protected ReferencedDocumentType buyerOrderReferencedDocument;
    @XmlElement(name = "QuotationReferencedDocument")
    protected ReferencedDocumentType quotationReferencedDocument;
    @XmlElement(name = "ContractReferencedDocument")
    protected ReferencedDocumentType contractReferencedDocument;
    @XmlElement(name = "BlanketOrderReferencedDocument")
    protected ReferencedDocumentType blanketOrderReferencedDocument;
    @XmlElement(name = "PreviousOrderReferencedDocument")
    protected ReferencedDocumentType previousOrderReferencedDocument;
    @XmlElement(name = "PreviousOrderChangeReferencedDocument")
    protected ReferencedDocumentType previousOrderChangeReferencedDocument;
    @XmlElement(name = "PreviousOrderResponseReferencedDocument")
    protected ReferencedDocumentType previousOrderResponseReferencedDocument;

    /**
     * Gets the value of the buyerReference property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getBuyerReference() {
        return buyerReference;
    }

    /**
     * Sets the value of the buyerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setBuyerReference(TextType value) {
        this.buyerReference = value;
    }

    /**
     * Gets the value of the sellerTradeParty property.
     * 
     * @return
     *     possible object is
     *     {@link TradePartyType }
     *     
     */
    public TradePartyType getSellerTradeParty() {
        return sellerTradeParty;
    }

    /**
     * Sets the value of the sellerTradeParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePartyType }
     *     
     */
    public void setSellerTradeParty(TradePartyType value) {
        this.sellerTradeParty = value;
    }

    /**
     * Gets the value of the buyerTradeParty property.
     * 
     * @return
     *     possible object is
     *     {@link TradePartyType }
     *     
     */
    public TradePartyType getBuyerTradeParty() {
        return buyerTradeParty;
    }

    /**
     * Sets the value of the buyerTradeParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradePartyType }
     *     
     */
    public void setBuyerTradeParty(TradePartyType value) {
        this.buyerTradeParty = value;
    }

    /**
     * Gets the value of the applicableTradeDeliveryTerms property.
     * 
     * @return
     *     possible object is
     *     {@link TradeDeliveryTermsType }
     *     
     */
    public TradeDeliveryTermsType getApplicableTradeDeliveryTerms() {
        return applicableTradeDeliveryTerms;
    }

    /**
     * Sets the value of the applicableTradeDeliveryTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeDeliveryTermsType }
     *     
     */
    public void setApplicableTradeDeliveryTerms(TradeDeliveryTermsType value) {
        this.applicableTradeDeliveryTerms = value;
    }

    /**
     * Gets the value of the buyerOrderReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getBuyerOrderReferencedDocument() {
        return buyerOrderReferencedDocument;
    }

    /**
     * Sets the value of the buyerOrderReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setBuyerOrderReferencedDocument(ReferencedDocumentType value) {
        this.buyerOrderReferencedDocument = value;
    }

    /**
     * Gets the value of the quotationReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getQuotationReferencedDocument() {
        return quotationReferencedDocument;
    }

    /**
     * Sets the value of the quotationReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setQuotationReferencedDocument(ReferencedDocumentType value) {
        this.quotationReferencedDocument = value;
    }

    /**
     * Gets the value of the contractReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getContractReferencedDocument() {
        return contractReferencedDocument;
    }

    /**
     * Sets the value of the contractReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setContractReferencedDocument(ReferencedDocumentType value) {
        this.contractReferencedDocument = value;
    }

    /**
     * Gets the value of the blanketOrderReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getBlanketOrderReferencedDocument() {
        return blanketOrderReferencedDocument;
    }

    /**
     * Sets the value of the blanketOrderReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setBlanketOrderReferencedDocument(ReferencedDocumentType value) {
        this.blanketOrderReferencedDocument = value;
    }

    /**
     * Gets the value of the previousOrderReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getPreviousOrderReferencedDocument() {
        return previousOrderReferencedDocument;
    }

    /**
     * Sets the value of the previousOrderReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setPreviousOrderReferencedDocument(ReferencedDocumentType value) {
        this.previousOrderReferencedDocument = value;
    }

    /**
     * Gets the value of the previousOrderChangeReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getPreviousOrderChangeReferencedDocument() {
        return previousOrderChangeReferencedDocument;
    }

    /**
     * Sets the value of the previousOrderChangeReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setPreviousOrderChangeReferencedDocument(ReferencedDocumentType value) {
        this.previousOrderChangeReferencedDocument = value;
    }

    /**
     * Gets the value of the previousOrderResponseReferencedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public ReferencedDocumentType getPreviousOrderResponseReferencedDocument() {
        return previousOrderResponseReferencedDocument;
    }

    /**
     * Sets the value of the previousOrderResponseReferencedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedDocumentType }
     *     
     */
    public void setPreviousOrderResponseReferencedDocument(ReferencedDocumentType value) {
        this.previousOrderResponseReferencedDocument = value;
    }

}
