//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 10:16:57 PM CET 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._103;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Supply Chain Trade Line Item
 * 
 * <p>Java class for SupplyChainTradeLineItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplyChainTradeLineItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssociatedDocumentLineDocument" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}DocumentLineDocumentType"/>
 *         &lt;element name="SpecifiedTradeProduct" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradeProductType" minOccurs="0"/>
 *         &lt;element name="SubstitutedReferencedProduct" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}ReferencedProductType" minOccurs="0"/>
 *         &lt;element name="SpecifiedLineTradeAgreement" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}LineTradeAgreementType"/>
 *         &lt;element name="SpecifiedLineTradeDelivery" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}LineTradeDeliveryType"/>
 *         &lt;element name="SpecifiedLineTradeSettlement" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}LineTradeSettlementType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplyChainTradeLineItemType", propOrder = {
    "associatedDocumentLineDocument",
    "specifiedTradeProduct",
    "substitutedReferencedProduct",
    "specifiedLineTradeAgreement",
    "specifiedLineTradeDelivery",
    "specifiedLineTradeSettlement"
})
public class SupplyChainTradeLineItemType {

    @XmlElement(name = "AssociatedDocumentLineDocument", required = true)
    protected DocumentLineDocumentType associatedDocumentLineDocument;
    @XmlElement(name = "SpecifiedTradeProduct")
    protected TradeProductType specifiedTradeProduct;
    @XmlElement(name = "SubstitutedReferencedProduct")
    protected ReferencedProductType substitutedReferencedProduct;
    @XmlElement(name = "SpecifiedLineTradeAgreement", required = true)
    protected LineTradeAgreementType specifiedLineTradeAgreement;
    @XmlElement(name = "SpecifiedLineTradeDelivery", required = true)
    protected LineTradeDeliveryType specifiedLineTradeDelivery;
    @XmlElement(name = "SpecifiedLineTradeSettlement", required = true)
    protected LineTradeSettlementType specifiedLineTradeSettlement;

    /**
     * Gets the value of the associatedDocumentLineDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentLineDocumentType }
     *     
     */
    public DocumentLineDocumentType getAssociatedDocumentLineDocument() {
        return associatedDocumentLineDocument;
    }

    /**
     * Sets the value of the associatedDocumentLineDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentLineDocumentType }
     *     
     */
    public void setAssociatedDocumentLineDocument(DocumentLineDocumentType value) {
        this.associatedDocumentLineDocument = value;
    }

    /**
     * Gets the value of the specifiedTradeProduct property.
     * 
     * @return
     *     possible object is
     *     {@link TradeProductType }
     *     
     */
    public TradeProductType getSpecifiedTradeProduct() {
        return specifiedTradeProduct;
    }

    /**
     * Sets the value of the specifiedTradeProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeProductType }
     *     
     */
    public void setSpecifiedTradeProduct(TradeProductType value) {
        this.specifiedTradeProduct = value;
    }

    /**
     * Gets the value of the substitutedReferencedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedProductType }
     *     
     */
    public ReferencedProductType getSubstitutedReferencedProduct() {
        return substitutedReferencedProduct;
    }

    /**
     * Sets the value of the substitutedReferencedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedProductType }
     *     
     */
    public void setSubstitutedReferencedProduct(ReferencedProductType value) {
        this.substitutedReferencedProduct = value;
    }

    /**
     * Gets the value of the specifiedLineTradeAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link LineTradeAgreementType }
     *     
     */
    public LineTradeAgreementType getSpecifiedLineTradeAgreement() {
        return specifiedLineTradeAgreement;
    }

    /**
     * Sets the value of the specifiedLineTradeAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineTradeAgreementType }
     *     
     */
    public void setSpecifiedLineTradeAgreement(LineTradeAgreementType value) {
        this.specifiedLineTradeAgreement = value;
    }

    /**
     * Gets the value of the specifiedLineTradeDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link LineTradeDeliveryType }
     *     
     */
    public LineTradeDeliveryType getSpecifiedLineTradeDelivery() {
        return specifiedLineTradeDelivery;
    }

    /**
     * Sets the value of the specifiedLineTradeDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineTradeDeliveryType }
     *     
     */
    public void setSpecifiedLineTradeDelivery(LineTradeDeliveryType value) {
        this.specifiedLineTradeDelivery = value;
    }

    /**
     * Gets the value of the specifiedLineTradeSettlement property.
     * 
     * @return
     *     possible object is
     *     {@link LineTradeSettlementType }
     *     
     */
    public LineTradeSettlementType getSpecifiedLineTradeSettlement() {
        return specifiedLineTradeSettlement;
    }

    /**
     * Sets the value of the specifiedLineTradeSettlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineTradeSettlementType }
     *     
     */
    public void setSpecifiedLineTradeSettlement(LineTradeSettlementType value) {
        this.specifiedLineTradeSettlement = value;
    }

}
