//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.10 at 09:19:13 PM CET 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._103;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import un.unece.uncefact.data.standard.unqualifieddatatype._103.IDType;
import un.unece.uncefact.data.standard.unqualifieddatatype._103.TextType;


/**
 * Trade Party
 * 
 * <p>Java class for TradePartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradePartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:103}IDType" minOccurs="0"/>
 *         &lt;element name="GlobalID" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:103}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:103}TextType" minOccurs="0"/>
 *         &lt;element name="SpecifiedLegalOrganization" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}LegalOrganizationType" minOccurs="0"/>
 *         &lt;element name="DefinedTradeContact" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradeContactType" minOccurs="0"/>
 *         &lt;element name="PostalTradeAddress" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TradeAddressType" minOccurs="0"/>
 *         &lt;element name="URIUniversalCommunication" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}UniversalCommunicationType" minOccurs="0"/>
 *         &lt;element name="SpecifiedTaxRegistration" type="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:103}TaxRegistrationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradePartyType", propOrder = {
    "id",
    "globalID",
    "name",
    "specifiedLegalOrganization",
    "definedTradeContact",
    "postalTradeAddress",
    "uriUniversalCommunication",
    "specifiedTaxRegistration"
})
public class TradePartyType {

    @XmlElement(name = "ID")
    protected IDType id;
    @XmlElement(name = "GlobalID")
    protected List<IDType> globalID;
    @XmlElement(name = "Name")
    protected TextType name;
    @XmlElement(name = "SpecifiedLegalOrganization")
    protected LegalOrganizationType specifiedLegalOrganization;
    @XmlElement(name = "DefinedTradeContact")
    protected TradeContactType definedTradeContact;
    @XmlElement(name = "PostalTradeAddress")
    protected TradeAddressType postalTradeAddress;
    @XmlElement(name = "URIUniversalCommunication")
    protected UniversalCommunicationType uriUniversalCommunication;
    @XmlElement(name = "SpecifiedTaxRegistration")
    protected TaxRegistrationType specifiedTaxRegistration;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setID(IDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the globalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlobalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getGlobalID() {
        if (globalID == null) {
            globalID = new ArrayList<IDType>();
        }
        return this.globalID;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setName(TextType value) {
        this.name = value;
    }

    /**
     * Gets the value of the specifiedLegalOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link LegalOrganizationType }
     *     
     */
    public LegalOrganizationType getSpecifiedLegalOrganization() {
        return specifiedLegalOrganization;
    }

    /**
     * Sets the value of the specifiedLegalOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalOrganizationType }
     *     
     */
    public void setSpecifiedLegalOrganization(LegalOrganizationType value) {
        this.specifiedLegalOrganization = value;
    }

    /**
     * Gets the value of the definedTradeContact property.
     * 
     * @return
     *     possible object is
     *     {@link TradeContactType }
     *     
     */
    public TradeContactType getDefinedTradeContact() {
        return definedTradeContact;
    }

    /**
     * Sets the value of the definedTradeContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeContactType }
     *     
     */
    public void setDefinedTradeContact(TradeContactType value) {
        this.definedTradeContact = value;
    }

    /**
     * Gets the value of the postalTradeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link TradeAddressType }
     *     
     */
    public TradeAddressType getPostalTradeAddress() {
        return postalTradeAddress;
    }

    /**
     * Sets the value of the postalTradeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeAddressType }
     *     
     */
    public void setPostalTradeAddress(TradeAddressType value) {
        this.postalTradeAddress = value;
    }

    /**
     * Gets the value of the uriUniversalCommunication property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalCommunicationType }
     *     
     */
    public UniversalCommunicationType getURIUniversalCommunication() {
        return uriUniversalCommunication;
    }

    /**
     * Sets the value of the uriUniversalCommunication property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalCommunicationType }
     *     
     */
    public void setURIUniversalCommunication(UniversalCommunicationType value) {
        this.uriUniversalCommunication = value;
    }

    /**
     * Gets the value of the specifiedTaxRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link TaxRegistrationType }
     *     
     */
    public TaxRegistrationType getSpecifiedTaxRegistration() {
        return specifiedTaxRegistration;
    }

    /**
     * Sets the value of the specifiedTaxRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxRegistrationType }
     *     
     */
    public void setSpecifiedTaxRegistration(TaxRegistrationType value) {
        this.specifiedTaxRegistration = value;
    }

}
