# GitHub Actions: example workflow
# see https://docs.github.com/en/actions/

name: build with gradle

# on: Controls when the action will run:
on: [push]

jobs:
  # see: https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
  build:
    # Ubuntu 16.04 is being deprecated Ubuntu 16.04 and will be removed on 2021-09-20
    # ubuntu-18.04 
    # ubuntu-latest is Ubuntu 20.04 
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Set up JDK
#        uses: actions/setup-java@v1.4.3
        uses: actions/setup-java@v2 # needs distribution
        with:
          java-version: '8'
          java-package: jdk
          distribution: 'adopt'
          
      - name: chmod # ./gradlew: Permission denied
        run: chmod 775 ./gradlew
        
      - name: Build with Gradle
        # see https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level
        run: ./gradlew --info build