//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COST_CATEGORY_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COST_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COST_ACCOUNT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "costcategoryid",
    "costtype",
    "costaccount"
})
@XmlRootElement(name = "ACCOUNTING_INFO")
public class ACCOUNTINGINFO {

    @XmlElement(name = "COST_CATEGORY_ID", required = true)
    protected COSTCATEGORYID costcategoryid;
    @XmlElement(name = "COST_TYPE")
    protected String costtype;
    @XmlElement(name = "COST_ACCOUNT")
    protected String costaccount;

    /**
     * Gets the value of the costcategoryid property.
     * 
     * @return
     *     possible object is
     *     {@link COSTCATEGORYID }
     *     
     */
    public COSTCATEGORYID getCOSTCATEGORYID() {
        return costcategoryid;
    }

    /**
     * Sets the value of the costcategoryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link COSTCATEGORYID }
     *     
     */
    public void setCOSTCATEGORYID(COSTCATEGORYID value) {
        this.costcategoryid = value;
    }

    /**
     * Gets the value of the costtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSTTYPE() {
        return costtype;
    }

    /**
     * Sets the value of the costtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSTTYPE(String value) {
        this.costtype = value;
    }

    /**
     * Gets the value of the costaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSTACCOUNT() {
        return costaccount;
    }

    /**
     * Sets the value of the costaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSTACCOUNT(String value) {
        this.costaccount = value;
    }

}
