//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FREF"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}FTEMPLATE"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIME_INFO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fref",
    "ftemplate",
    "mimeinfo"
})
@XmlRootElement(name = "CONFIG_FEATURE")
public class CONFIGFEATURE {

    @XmlElement(name = "FREF")
    protected FREF fref;
    @XmlElement(name = "FTEMPLATE")
    protected TypeFTEMPLATE ftemplate;
    @XmlElement(name = "MIME_INFO")
    protected MIMEINFO mimeinfo;

    /**
     * Gets the value of the fref property.
     * 
     * @return
     *     possible object is
     *     {@link FREF }
     *     
     */
    public FREF getFREF() {
        return fref;
    }

    /**
     * Sets the value of the fref property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREF }
     *     
     */
    public void setFREF(FREF value) {
        this.fref = value;
    }

    /**
     * Gets the value of the ftemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TypeFTEMPLATE }
     *     
     */
    public TypeFTEMPLATE getFTEMPLATE() {
        return ftemplate;
    }

    /**
     * Sets the value of the ftemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeFTEMPLATE }
     *     
     */
    public void setFTEMPLATE(TypeFTEMPLATE value) {
        this.ftemplate = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link MIMEINFO }
     *     
     */
    public MIMEINFO getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIMEINFO }
     *     
     */
    public void setMIMEINFO(MIMEINFO value) {
        this.mimeinfo = value;
    }

}
