//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_HEADER" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_DESCR_SHORT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_DESCR_LONG" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_ORDER" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STEP_INTERACTION_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_CODE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PRODUCT_PRICE_DETAILS" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_FEATURE"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONFIG_PARTS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MIN_OCCURANCE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}MAX_OCCURANCE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stepid",
    "stepheader",
    "stepdescrshort",
    "stepdescrlong",
    "steporder",
    "stepinteractiontype",
    "configcode",
    "productpricedetails",
    "configfeature",
    "configparts",
    "minoccurance",
    "maxoccurance"
})
@XmlRootElement(name = "CONFIG_STEP")
public class CONFIGSTEP {

    @XmlElement(name = "STEP_ID", required = true)
    protected String stepid;
    @XmlElement(name = "STEP_HEADER", required = true)
    protected List<STEPHEADER> stepheader;
    @XmlElement(name = "STEP_DESCR_SHORT")
    protected List<STEPDESCRSHORT> stepdescrshort;
    @XmlElement(name = "STEP_DESCR_LONG")
    protected List<STEPDESCRLONG> stepdescrlong;
    @XmlElement(name = "STEP_ORDER")
    protected BigInteger steporder;
    @XmlElement(name = "STEP_INTERACTION_TYPE", defaultValue = "force_userinput")
    protected String stepinteractiontype;
    @XmlElement(name = "CONFIG_CODE")
    protected String configcode;
    @XmlElement(name = "PRODUCT_PRICE_DETAILS")
    protected PRODUCTPRICEDETAILS productpricedetails;
    @XmlElement(name = "CONFIG_FEATURE")
    protected CONFIGFEATURE configfeature;
    @XmlElement(name = "CONFIG_PARTS")
    protected CONFIGPARTS configparts;
    @XmlElement(name = "MIN_OCCURANCE", required = true)
    protected BigInteger minoccurance;
    @XmlElement(name = "MAX_OCCURANCE", required = true)
    protected BigInteger maxoccurance;

    /**
     * Gets the value of the stepid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTEPID() {
        return stepid;
    }

    /**
     * Sets the value of the stepid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTEPID(String value) {
        this.stepid = value;
    }

    /**
     * Gets the value of the stepheader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stepheader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTEPHEADER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STEPHEADER }
     * 
     * 
     */
    public List<STEPHEADER> getSTEPHEADER() {
        if (stepheader == null) {
            stepheader = new ArrayList<STEPHEADER>();
        }
        return this.stepheader;
    }

    /**
     * Gets the value of the stepdescrshort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stepdescrshort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTEPDESCRSHORT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STEPDESCRSHORT }
     * 
     * 
     */
    public List<STEPDESCRSHORT> getSTEPDESCRSHORT() {
        if (stepdescrshort == null) {
            stepdescrshort = new ArrayList<STEPDESCRSHORT>();
        }
        return this.stepdescrshort;
    }

    /**
     * Gets the value of the stepdescrlong property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stepdescrlong property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTEPDESCRLONG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STEPDESCRLONG }
     * 
     * 
     */
    public List<STEPDESCRLONG> getSTEPDESCRLONG() {
        if (stepdescrlong == null) {
            stepdescrlong = new ArrayList<STEPDESCRLONG>();
        }
        return this.stepdescrlong;
    }

    /**
     * Gets the value of the steporder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTEPORDER() {
        return steporder;
    }

    /**
     * Sets the value of the steporder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTEPORDER(BigInteger value) {
        this.steporder = value;
    }

    /**
     * Gets the value of the stepinteractiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTEPINTERACTIONTYPE() {
        return stepinteractiontype;
    }

    /**
     * Sets the value of the stepinteractiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTEPINTERACTIONTYPE(String value) {
        this.stepinteractiontype = value;
    }

    /**
     * Gets the value of the configcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIGCODE() {
        return configcode;
    }

    /**
     * Sets the value of the configcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIGCODE(String value) {
        this.configcode = value;
    }

    /**
     * Gets the value of the productpricedetails property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTPRICEDETAILS }
     *     
     */
    public PRODUCTPRICEDETAILS getPRODUCTPRICEDETAILS() {
        return productpricedetails;
    }

    /**
     * Sets the value of the productpricedetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTPRICEDETAILS }
     *     
     */
    public void setPRODUCTPRICEDETAILS(PRODUCTPRICEDETAILS value) {
        this.productpricedetails = value;
    }

    /**
     * Gets the value of the configfeature property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIGFEATURE }
     *     
     */
    public CONFIGFEATURE getCONFIGFEATURE() {
        return configfeature;
    }

    /**
     * Sets the value of the configfeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIGFEATURE }
     *     
     */
    public void setCONFIGFEATURE(CONFIGFEATURE value) {
        this.configfeature = value;
    }

    /**
     * Gets the value of the configparts property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIGPARTS }
     *     
     */
    public CONFIGPARTS getCONFIGPARTS() {
        return configparts;
    }

    /**
     * Sets the value of the configparts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIGPARTS }
     *     
     */
    public void setCONFIGPARTS(CONFIGPARTS value) {
        this.configparts = value;
    }

    /**
     * Gets the value of the minoccurance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMINOCCURANCE() {
        return minoccurance;
    }

    /**
     * Sets the value of the minoccurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMINOCCURANCE(BigInteger value) {
        this.minoccurance = value;
    }

    /**
     * Gets the value of the maxoccurance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMAXOCCURANCE() {
        return maxoccurance;
    }

    /**
     * Sets the value of the maxoccurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMAXOCCURANCE(BigInteger value) {
        this.maxoccurance = value;
    }

}
