//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PART_ALTERNATIVE" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PART_SELECTION_TYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partalternative",
    "partselectiontype"
})
@XmlRootElement(name = "CONFIG_PARTS")
public class CONFIGPARTS {

    @XmlElement(name = "PART_ALTERNATIVE", required = true)
    protected List<PARTALTERNATIVE> partalternative;
    @XmlElement(name = "PART_SELECTION_TYPE", defaultValue = "non-distinct")
    protected String partselectiontype;

    /**
     * Gets the value of the partalternative property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partalternative property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPARTALTERNATIVE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PARTALTERNATIVE }
     * 
     * 
     */
    public List<PARTALTERNATIVE> getPARTALTERNATIVE() {
        if (partalternative == null) {
            partalternative = new ArrayList<PARTALTERNATIVE>();
        }
        return this.partalternative;
    }

    /**
     * Gets the value of the partselectiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTSELECTIONTYPE() {
        return partselectiontype;
    }

    /**
     * Sets the value of the partselectiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTSELECTIONTYPE(String value) {
        this.partselectiontype = value;
    }

}
