//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_LANGUAGES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_TERRITORIES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRICE_CURRENCIES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRICE_TYPES" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_SUPPLIER_PID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRODUCTCONFIG_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PRODUCTLIST_IDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_USER_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_AUTHENTIFICATION_INFO" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_PARAM_DEFINITION" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ipplanguages",
    "ippterritories",
    "ipppricecurrencies",
    "ipppricetypes",
    "ippsupplierpid",
    "ippproductconfigidref",
    "ippproductlistidref",
    "ippuserinfo",
    "ippauthentificationinfo",
    "ippparamdefinition"
})
@XmlRootElement(name = "IPP_OUTBOUND_PARAMS")
public class IPPOUTBOUNDPARAMS {

    @XmlElement(name = "IPP_LANGUAGES")
    protected IPPLANGUAGES ipplanguages;
    @XmlElement(name = "IPP_TERRITORIES")
    protected IPPTERRITORIES ippterritories;
    @XmlElement(name = "IPP_PRICE_CURRENCIES")
    protected IPPPRICECURRENCIES ipppricecurrencies;
    @XmlElement(name = "IPP_PRICE_TYPES")
    protected IPPPRICETYPES ipppricetypes;
    @XmlElement(name = "IPP_SUPPLIER_PID")
    protected IPPSUPPLIERPID ippsupplierpid;
    @XmlElement(name = "IPP_PRODUCTCONFIG_IDREF")
    protected IPPPRODUCTCONFIGIDREF ippproductconfigidref;
    @XmlElement(name = "IPP_PRODUCTLIST_IDREF")
    protected IPPPRODUCTLISTIDREF ippproductlistidref;
    @XmlElement(name = "IPP_USER_INFO")
    protected IPPUSERINFO ippuserinfo;
    @XmlElement(name = "IPP_AUTHENTIFICATION_INFO")
    protected IPPAUTHENTIFICATIONINFO ippauthentificationinfo;
    @XmlElement(name = "IPP_PARAM_DEFINITION")
    protected List<IPPPARAMDEFINITION> ippparamdefinition;

    /**
     * Gets the value of the ipplanguages property.
     * 
     * @return
     *     possible object is
     *     {@link IPPLANGUAGES }
     *     
     */
    public IPPLANGUAGES getIPPLANGUAGES() {
        return ipplanguages;
    }

    /**
     * Sets the value of the ipplanguages property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPLANGUAGES }
     *     
     */
    public void setIPPLANGUAGES(IPPLANGUAGES value) {
        this.ipplanguages = value;
    }

    /**
     * Gets the value of the ippterritories property.
     * 
     * @return
     *     possible object is
     *     {@link IPPTERRITORIES }
     *     
     */
    public IPPTERRITORIES getIPPTERRITORIES() {
        return ippterritories;
    }

    /**
     * Sets the value of the ippterritories property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPTERRITORIES }
     *     
     */
    public void setIPPTERRITORIES(IPPTERRITORIES value) {
        this.ippterritories = value;
    }

    /**
     * Gets the value of the ipppricecurrencies property.
     * 
     * @return
     *     possible object is
     *     {@link IPPPRICECURRENCIES }
     *     
     */
    public IPPPRICECURRENCIES getIPPPRICECURRENCIES() {
        return ipppricecurrencies;
    }

    /**
     * Sets the value of the ipppricecurrencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPPRICECURRENCIES }
     *     
     */
    public void setIPPPRICECURRENCIES(IPPPRICECURRENCIES value) {
        this.ipppricecurrencies = value;
    }

    /**
     * Gets the value of the ipppricetypes property.
     * 
     * @return
     *     possible object is
     *     {@link IPPPRICETYPES }
     *     
     */
    public IPPPRICETYPES getIPPPRICETYPES() {
        return ipppricetypes;
    }

    /**
     * Sets the value of the ipppricetypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPPRICETYPES }
     *     
     */
    public void setIPPPRICETYPES(IPPPRICETYPES value) {
        this.ipppricetypes = value;
    }

    /**
     * Gets the value of the ippsupplierpid property.
     * 
     * @return
     *     possible object is
     *     {@link IPPSUPPLIERPID }
     *     
     */
    public IPPSUPPLIERPID getIPPSUPPLIERPID() {
        return ippsupplierpid;
    }

    /**
     * Sets the value of the ippsupplierpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPSUPPLIERPID }
     *     
     */
    public void setIPPSUPPLIERPID(IPPSUPPLIERPID value) {
        this.ippsupplierpid = value;
    }

    /**
     * Gets the value of the ippproductconfigidref property.
     * 
     * @return
     *     possible object is
     *     {@link IPPPRODUCTCONFIGIDREF }
     *     
     */
    public IPPPRODUCTCONFIGIDREF getIPPPRODUCTCONFIGIDREF() {
        return ippproductconfigidref;
    }

    /**
     * Sets the value of the ippproductconfigidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPPRODUCTCONFIGIDREF }
     *     
     */
    public void setIPPPRODUCTCONFIGIDREF(IPPPRODUCTCONFIGIDREF value) {
        this.ippproductconfigidref = value;
    }

    /**
     * Gets the value of the ippproductlistidref property.
     * 
     * @return
     *     possible object is
     *     {@link IPPPRODUCTLISTIDREF }
     *     
     */
    public IPPPRODUCTLISTIDREF getIPPPRODUCTLISTIDREF() {
        return ippproductlistidref;
    }

    /**
     * Sets the value of the ippproductlistidref property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPPRODUCTLISTIDREF }
     *     
     */
    public void setIPPPRODUCTLISTIDREF(IPPPRODUCTLISTIDREF value) {
        this.ippproductlistidref = value;
    }

    /**
     * Gets the value of the ippuserinfo property.
     * 
     * @return
     *     possible object is
     *     {@link IPPUSERINFO }
     *     
     */
    public IPPUSERINFO getIPPUSERINFO() {
        return ippuserinfo;
    }

    /**
     * Sets the value of the ippuserinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPUSERINFO }
     *     
     */
    public void setIPPUSERINFO(IPPUSERINFO value) {
        this.ippuserinfo = value;
    }

    /**
     * Gets the value of the ippauthentificationinfo property.
     * 
     * @return
     *     possible object is
     *     {@link IPPAUTHENTIFICATIONINFO }
     *     
     */
    public IPPAUTHENTIFICATIONINFO getIPPAUTHENTIFICATIONINFO() {
        return ippauthentificationinfo;
    }

    /**
     * Sets the value of the ippauthentificationinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPPAUTHENTIFICATIONINFO }
     *     
     */
    public void setIPPAUTHENTIFICATIONINFO(IPPAUTHENTIFICATIONINFO value) {
        this.ippauthentificationinfo = value;
    }

    /**
     * Gets the value of the ippparamdefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippparamdefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPPARAMDEFINITION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IPPPARAMDEFINITION }
     * 
     * 
     */
    public List<IPPPARAMDEFINITION> getIPPPARAMDEFINITION() {
        if (ippparamdefinition == null) {
            ippparamdefinition = new ArrayList<IPPPARAMDEFINITION>();
        }
        return this.ippparamdefinition;
    }

}
