//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_OPERATION_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_OPERATION_TYPE"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_OPERATION_DESCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_OUTBOUND" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}IPP_INBOUND" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ippoperationid",
    "ippoperationtype",
    "ippoperationdescr",
    "ippoutbound",
    "ippinbound"
})
@XmlRootElement(name = "IPP_OPERATION")
public class IPPOPERATION {

    @XmlElement(name = "IPP_OPERATION_ID", required = true)
    protected String ippoperationid;
    @XmlElement(name = "IPP_OPERATION_TYPE", required = true)
    protected String ippoperationtype;
    @XmlElement(name = "IPP_OPERATION_DESCR")
    protected List<IPPOPERATIONDESCR> ippoperationdescr;
    @XmlElement(name = "IPP_OUTBOUND", required = true)
    protected List<IPPOUTBOUND> ippoutbound;
    @XmlElement(name = "IPP_INBOUND", required = true)
    protected List<IPPINBOUND> ippinbound;

    /**
     * Gets the value of the ippoperationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPPOPERATIONID() {
        return ippoperationid;
    }

    /**
     * Sets the value of the ippoperationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPPOPERATIONID(String value) {
        this.ippoperationid = value;
    }

    /**
     * Gets the value of the ippoperationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPPOPERATIONTYPE() {
        return ippoperationtype;
    }

    /**
     * Sets the value of the ippoperationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPPOPERATIONTYPE(String value) {
        this.ippoperationtype = value;
    }

    /**
     * Gets the value of the ippoperationdescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippoperationdescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPOPERATIONDESCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IPPOPERATIONDESCR }
     * 
     * 
     */
    public List<IPPOPERATIONDESCR> getIPPOPERATIONDESCR() {
        if (ippoperationdescr == null) {
            ippoperationdescr = new ArrayList<IPPOPERATIONDESCR>();
        }
        return this.ippoperationdescr;
    }

    /**
     * Gets the value of the ippoutbound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippoutbound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPOUTBOUND().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IPPOUTBOUND }
     * 
     * 
     */
    public List<IPPOUTBOUND> getIPPOUTBOUND() {
        if (ippoutbound == null) {
            ippoutbound = new ArrayList<IPPOUTBOUND>();
        }
        return this.ippoutbound;
    }

    /**
     * Gets the value of the ippinbound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ippinbound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPPINBOUND().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IPPINBOUND }
     * 
     * 
     */
    public List<IPPINBOUND> getIPPINBOUND() {
        if (ippinbound == null) {
            ippinbound = new ArrayList<IPPINBOUND>();
        }
        return this.ippinbound;
    }

}
