//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_SYMBOLREF"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PARAMETER_VALUE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parametersymbolref",
    "parametervalue"
})
@XmlRootElement(name = "PARAMETER")
public class PARAMETER {

    @XmlElement(name = "PARAMETER_SYMBOLREF", required = true)
    protected String parametersymbolref;
    @XmlElement(name = "PARAMETER_VALUE", required = true)
    protected String parametervalue;

    /**
     * Gets the value of the parametersymbolref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARAMETERSYMBOLREF() {
        return parametersymbolref;
    }

    /**
     * Sets the value of the parametersymbolref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARAMETERSYMBOLREF(String value) {
        this.parametersymbolref = value;
    }

    /**
     * Gets the value of the parametervalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARAMETERVALUE() {
        return parametervalue;
    }

    /**
     * Sets the value of the parametervalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARAMETERVALUE(String value) {
        this.parametervalue = value;
    }

}
