//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CALCULATION_SEQUENCE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TAX_CATEGORY" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TAX_TYPE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TAX" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}EXEMPTION_REASON" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}JURISDICTION" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "calculationsequence",
    "taxcategory",
    "taxtype",
    "tax",
    "exemptionreason",
    "jurisdiction"
})
@XmlRootElement(name = "TAX_DETAILS")
public class TAXDETAILS {

    @XmlElement(name = "CALCULATION_SEQUENCE", defaultValue = "1")
    protected BigInteger calculationsequence;
    @XmlElement(name = "TAX_CATEGORY")
    protected String taxcategory;
    @XmlElement(name = "TAX_TYPE", defaultValue = "vat")
    protected String taxtype;
    @XmlElement(name = "TAX")
    protected BigDecimal tax;
    @XmlElement(name = "EXEMPTION_REASON")
    protected List<EXEMPTIONREASON> exemptionreason;
    @XmlElement(name = "JURISDICTION")
    protected List<JURISDICTION> jurisdiction;

    /**
     * Gets the value of the calculationsequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCALCULATIONSEQUENCE() {
        return calculationsequence;
    }

    /**
     * Sets the value of the calculationsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCALCULATIONSEQUENCE(BigInteger value) {
        this.calculationsequence = value;
    }

    /**
     * Gets the value of the taxcategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXCATEGORY() {
        return taxcategory;
    }

    /**
     * Sets the value of the taxcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXCATEGORY(String value) {
        this.taxcategory = value;
    }

    /**
     * Gets the value of the taxtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXTYPE() {
        return taxtype;
    }

    /**
     * Sets the value of the taxtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXTYPE(String value) {
        this.taxtype = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAX() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAX(BigDecimal value) {
        this.tax = value;
    }

    /**
     * Gets the value of the exemptionreason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exemptionreason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXEMPTIONREASON().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXEMPTIONREASON }
     * 
     * 
     */
    public List<EXEMPTIONREASON> getEXEMPTIONREASON() {
        if (exemptionreason == null) {
            exemptionreason = new ArrayList<EXEMPTIONREASON>();
        }
        return this.exemptionreason;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jurisdiction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJURISDICTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JURISDICTION }
     * 
     * 
     */
    public List<JURISDICTION> getJURISDICTION() {
        if (jurisdiction == null) {
            jurisdiction = new ArrayList<JURISDICTION>();
        }
        return this.jurisdiction;
    }

}
