//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERM_ID"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERM_CONDITION" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}TERM_EXPRESSION"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" default="function">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.bmecat.org/bmecat/2005}dtSTRING">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *             &lt;enumeration value="function"/>
 *             &lt;enumeration value="constraint"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "termid",
    "termcondition",
    "termexpression"
})
@XmlRootElement(name = "TERM")
public class TERM {

    @XmlElement(name = "TERM_ID", required = true)
    protected String termid;
    @XmlElement(name = "TERM_CONDITION")
    protected String termcondition;
    @XmlElement(name = "TERM_EXPRESSION", required = true)
    protected String termexpression;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the termid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMID() {
        return termid;
    }

    /**
     * Sets the value of the termid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMID(String value) {
        this.termid = value;
    }

    /**
     * Gets the value of the termcondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMCONDITION() {
        return termcondition;
    }

    /**
     * Sets the value of the termcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMCONDITION(String value) {
        this.termcondition = value;
    }

    /**
     * Gets the value of the termexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMEXPRESSION() {
        return termexpression;
    }

    /**
     * Sets the value of the termexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMEXPRESSION(String value) {
        this.termexpression = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "function";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
