//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeVERSION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeVERSION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VERSION"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VERSION_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}REVISION" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}REVISION_DATE" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ORIGINAL_DATE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeVERSION", propOrder = {
    "version",
    "versiondate",
    "revision",
    "revisiondate",
    "originaldate"
})
public class TypeVERSION {

    @XmlElement(name = "VERSION", required = true)
    protected String version;
    @XmlElement(name = "VERSION_DATE")
    protected String versiondate;
    @XmlElement(name = "REVISION")
    protected String revision;
    @XmlElement(name = "REVISION_DATE")
    protected String revisiondate;
    @XmlElement(name = "ORIGINAL_DATE")
    protected String originaldate;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the versiondate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSIONDATE() {
        return versiondate;
    }

    /**
     * Sets the value of the versiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSIONDATE(String value) {
        this.versiondate = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREVISION(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the revisiondate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREVISIONDATE() {
        return revisiondate;
    }

    /**
     * Sets the value of the revisiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREVISIONDATE(String value) {
        this.revisiondate = value;
    }

    /**
     * Gets the value of the originaldate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINALDATE() {
        return originaldate;
    }

    /**
     * Sets the value of the originaldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINALDATE(String value) {
        this.originaldate = value;
    }

}
