//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.22 at 08:34:27 PM CET 
//


package org.bmecat.bmecat._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeADDRESS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeADDRESS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}NAME2" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}NAME3" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}DEPARTMENT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONTACT_DETAILS" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}CONTACT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STREET" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ZIP" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}BOXNO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ZIPBOX" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}CITY" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}STATE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COUNTRY" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}COUNTRY_CODED" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}VAT_ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}PHONE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}FAX" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}EMAIL"/>
 *           &lt;element ref="{http://www.bmecat.org/bmecat/2005}PUBLIC_KEY" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}URL" minOccurs="0"/>
 *         &lt;element ref="{http://www.bmecat.org/bmecat/2005}ADDRESS_REMARKS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeADDRESS", propOrder = {
    "name",
    "name2",
    "name3",
    "department",
    "contactdetails",
    "contact",
    "street",
    "zip",
    "boxno",
    "zipbox",
    "city",
    "state",
    "country",
    "countrycoded",
    "vatid",
    "phone",
    "fax",
    "emailAndPUBLICKEY",
    "url",
    "addressremarks"
})
@XmlSeeAlso({
    org.bmecat.bmecat._2005.BUYER.ADDRESS.class,
    org.bmecat.bmecat._2005.SUPPLIER.ADDRESS.class
})
public class TypeADDRESS {

    @XmlElement(name = "NAME")
    protected List<NAME> name;
    @XmlElement(name = "NAME2")
    protected List<NAME2> name2;
    @XmlElement(name = "NAME3")
    protected List<NAME3> name3;
    @XmlElement(name = "DEPARTMENT")
    protected List<DEPARTMENT> department;
    @XmlElement(name = "CONTACT_DETAILS")
    protected List<CONTACTDETAILS> contactdetails;
    @XmlElement(name = "CONTACT")
    protected List<CONTACT> contact;
    @XmlElement(name = "STREET")
    protected List<STREET> street;
    @XmlElement(name = "ZIP")
    protected List<ZIP> zip;
    @XmlElement(name = "BOXNO")
    protected List<BOXNO> boxno;
    @XmlElement(name = "ZIPBOX")
    protected List<ZIPBOX> zipbox;
    @XmlElement(name = "CITY")
    protected List<CITY> city;
    @XmlElement(name = "STATE")
    protected List<STATE> state;
    @XmlElement(name = "COUNTRY")
    protected List<COUNTRY> country;
    @XmlElement(name = "COUNTRY_CODED")
    protected String countrycoded;
    @XmlElement(name = "VAT_ID")
    protected String vatid;
    @XmlElement(name = "PHONE")
    protected List<PHONE> phone;
    @XmlElement(name = "FAX")
    protected List<FAX> fax;
    @XmlElements({
        @XmlElement(name = "EMAIL", type = String.class),
        @XmlElement(name = "PUBLIC_KEY", type = PUBLICKEY.class)
    })
    protected List<Object> emailAndPUBLICKEY;
    @XmlElement(name = "URL")
    protected String url;
    @XmlElement(name = "ADDRESS_REMARKS")
    protected List<ADDRESSREMARKS> addressremarks;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAME }
     * 
     * 
     */
    public List<NAME> getNAME() {
        if (name == null) {
            name = new ArrayList<NAME>();
        }
        return this.name;
    }

    /**
     * Gets the value of the name2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAME2 }
     * 
     * 
     */
    public List<NAME2> getNAME2() {
        if (name2 == null) {
            name2 = new ArrayList<NAME2>();
        }
        return this.name2;
    }

    /**
     * Gets the value of the name3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAME3 }
     * 
     * 
     */
    public List<NAME3> getNAME3() {
        if (name3 == null) {
            name3 = new ArrayList<NAME3>();
        }
        return this.name3;
    }

    /**
     * Gets the value of the department property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the department property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEPARTMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEPARTMENT }
     * 
     * 
     */
    public List<DEPARTMENT> getDEPARTMENT() {
        if (department == null) {
            department = new ArrayList<DEPARTMENT>();
        }
        return this.department;
    }

    /**
     * Gets the value of the contactdetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactdetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACTDETAILS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONTACTDETAILS }
     * 
     * 
     */
    public List<CONTACTDETAILS> getCONTACTDETAILS() {
        if (contactdetails == null) {
            contactdetails = new ArrayList<CONTACTDETAILS>();
        }
        return this.contactdetails;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONTACT }
     * 
     * 
     */
    public List<CONTACT> getCONTACT() {
        if (contact == null) {
            contact = new ArrayList<CONTACT>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the street property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the street property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTREET().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STREET }
     * 
     * 
     */
    public List<STREET> getSTREET() {
        if (street == null) {
            street = new ArrayList<STREET>();
        }
        return this.street;
    }

    /**
     * Gets the value of the zip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZIP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZIP }
     * 
     * 
     */
    public List<ZIP> getZIP() {
        if (zip == null) {
            zip = new ArrayList<ZIP>();
        }
        return this.zip;
    }

    /**
     * Gets the value of the boxno property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boxno property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBOXNO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BOXNO }
     * 
     * 
     */
    public List<BOXNO> getBOXNO() {
        if (boxno == null) {
            boxno = new ArrayList<BOXNO>();
        }
        return this.boxno;
    }

    /**
     * Gets the value of the zipbox property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zipbox property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZIPBOX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZIPBOX }
     * 
     * 
     */
    public List<ZIPBOX> getZIPBOX() {
        if (zipbox == null) {
            zipbox = new ArrayList<ZIPBOX>();
        }
        return this.zipbox;
    }

    /**
     * Gets the value of the city property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the city property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCITY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CITY }
     * 
     * 
     */
    public List<CITY> getCITY() {
        if (city == null) {
            city = new ArrayList<CITY>();
        }
        return this.city;
    }

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTATE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STATE }
     * 
     * 
     */
    public List<STATE> getSTATE() {
        if (state == null) {
            state = new ArrayList<STATE>();
        }
        return this.state;
    }

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOUNTRY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COUNTRY }
     * 
     * 
     */
    public List<COUNTRY> getCOUNTRY() {
        if (country == null) {
            country = new ArrayList<COUNTRY>();
        }
        return this.country;
    }

    /**
     * Gets the value of the countrycoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYCODED() {
        return countrycoded;
    }

    /**
     * Sets the value of the countrycoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYCODED(String value) {
        this.countrycoded = value;
    }

    /**
     * Gets the value of the vatid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATID() {
        return vatid;
    }

    /**
     * Sets the value of the vatid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATID(String value) {
        this.vatid = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPHONE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PHONE }
     * 
     * 
     */
    public List<PHONE> getPHONE() {
        if (phone == null) {
            phone = new ArrayList<PHONE>();
        }
        return this.phone;
    }

    /**
     * Gets the value of the fax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFAX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FAX }
     * 
     * 
     */
    public List<FAX> getFAX() {
        if (fax == null) {
            fax = new ArrayList<FAX>();
        }
        return this.fax;
    }

    /**
     * Gets the value of the emailAndPUBLICKEY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailAndPUBLICKEY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMAILAndPUBLICKEY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link PUBLICKEY }
     * 
     * 
     */
    public List<Object> getEMAILAndPUBLICKEY() {
        if (emailAndPUBLICKEY == null) {
            emailAndPUBLICKEY = new ArrayList<Object>();
        }
        return this.emailAndPUBLICKEY;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the addressremarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressremarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADDRESSREMARKS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ADDRESSREMARKS }
     * 
     * 
     */
    public List<ADDRESSREMARKS> getADDRESSREMARKS() {
        if (addressremarks == null) {
            addressremarks = new ArrayList<ADDRESSREMARKS>();
        }
        return this.addressremarks;
    }

}
